default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV['DB_USERNAME'] || 'ai_splitwise_clone' %>
  password: <%= ENV['DB_PASSWORD'] || 'ai_splitwise_clone' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ai_splitwise_clone_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
